Output "media/demo.gif"
Set Shell fish
Set FontSize 19
Set Width 1280
Set Height 720
Set FontFamily "jetbrainsmono nfm"
Set Theme "Catppuccin Macchiato"
Set WindowBar Colorful
Set Framerate 60


Type "ape_call --help"
Enter 1
Sleep 2s
Type "ape_call call --function-sig 'call_this_view_function(uint256)(string)' --address '0x80E097a70cacA11EB71B6401FB12D48A1A61Ef54' --args 6147190"
Enter 1
Sleep 10s
