name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python_version: ['3.9']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install hatch pre-commit
        hatch env create
    - name: Lint and typecheck
      run: |
        hatch run lint:lint-check
    # - name: Run Tests
    #   run: |
    #     hatch run test:pytest
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        verbose: true

  release:
    runs-on: ubuntu-latest
    environment: release
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
        contents: write
        id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install hatch pre-commit
    - name: Build
      run: |
        hatch build
    - name: Publish 📦 to Test PyPI
      # As the github.ref will come from release tag that's why it's commented out
      # if: startsWith(github.ref, 'refs/heads/main')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        skip_existing: true
        user: __token__
        password: ${{ secrets.TEST_PYPI_SECRECT }}
        verbose: true
        # packages-dir: dist/
        repository-url: https://test.pypi.org/legacy/
    - name: Publish 📦 to PyPI
      # if: startsWith(github.ref, 'refs/heads/main')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_SECRECT }}
        verbose: true
        # packages-dir: dist/
